name: Derius-Woodcutting
version: 0.1_dev
main: dk.muj.derius.woodcutting.DeriusWoodcutting
#website: http://muj.dk/Derius/Woodcutting
authors: [Ulumulu1510, Madus]
description: <e>Woodcutting skill for the Derius skill framework.
depend: [Derius-Core]
load: startup
